// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using db_projektarbeit.Model;

namespace db_projektarbeit.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20210124201954_intial")]
    partial class intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.HasSequence<int>("CustomerNr", "shared")
                .StartsAt(1000L);

            modelBuilder.HasSequence<int>("ProductNr", "shared")
                .StartsAt(10000L);

            modelBuilder.Entity("db_projektarbeit.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "St. Gallen",
                            Zip = 9000
                        },
                        new
                        {
                            Id = 2,
                            Name = "Niederuzwil",
                            Zip = 9244
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bettwiesen",
                            Zip = 9553
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rebstein",
                            Zip = 9445
                        },
                        new
                        {
                            Id = 5,
                            Name = "Goldach",
                            Zip = 9403
                        },
                        new
                        {
                            Id = 6,
                            Name = "Rorschach",
                            Zip = 9400
                        },
                        new
                        {
                            Id = 7,
                            Name = "Au",
                            Zip = 9434
                        },
                        new
                        {
                            Id = 8,
                            Name = "Diepoldsau",
                            Zip = 9444
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sevelen",
                            Zip = 9475
                        },
                        new
                        {
                            Id = 10,
                            Name = "Mörschwil",
                            Zip = 9402
                        },
                        new
                        {
                            Id = 11,
                            Name = "Arbon",
                            Zip = 9320
                        },
                        new
                        {
                            Id = 12,
                            Name = "Tübach",
                            Zip = 9327
                        },
                        new
                        {
                            Id = 13,
                            Name = "Berg (SG)",
                            Zip = 9305
                        },
                        new
                        {
                            Id = 14,
                            Name = "Teufen",
                            Zip = 9053
                        },
                        new
                        {
                            Id = 15,
                            Name = "Gais",
                            Zip = 9056
                        },
                        new
                        {
                            Id = 16,
                            Name = "Rehetobel",
                            Zip = 9038
                        },
                        new
                        {
                            Id = 17,
                            Name = "Trogen",
                            Zip = 9043
                        },
                        new
                        {
                            Id = 18,
                            Name = "Grub",
                            Zip = 9035
                        },
                        new
                        {
                            Id = 19,
                            Name = "Hundwil",
                            Zip = 9064
                        },
                        new
                        {
                            Id = 20,
                            Name = "Untereggen",
                            Zip = 9033
                        },
                        new
                        {
                            Id = 21,
                            Name = "Gossau",
                            Zip = 9200
                        },
                        new
                        {
                            Id = 22,
                            Name = "Flawil",
                            Zip = 9230
                        },
                        new
                        {
                            Id = 23,
                            Name = "Bischofszell",
                            Zip = 9220
                        },
                        new
                        {
                            Id = 24,
                            Name = "Oberbüren",
                            Zip = 9245
                        },
                        new
                        {
                            Id = 25,
                            Name = "Jonschwil",
                            Zip = 9243
                        },
                        new
                        {
                            Id = 26,
                            Name = "Andwil (SG)",
                            Zip = 9204
                        },
                        new
                        {
                            Id = 27,
                            Name = "Hohentannen",
                            Zip = 9216
                        },
                        new
                        {
                            Id = 28,
                            Name = "Rheineck",
                            Zip = 9424
                        },
                        new
                        {
                            Id = 29,
                            Name = "Buchs",
                            Zip = 9470
                        },
                        new
                        {
                            Id = 30,
                            Name = "Thal",
                            Zip = 9425
                        });
                });

            modelBuilder.Entity("db_projektarbeit.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR shared.CustomerNr");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 2,
                            CompanyName = "Traber Corp",
                            CustomerNr = 0,
                            FirstName = "Marc",
                            HouseNumber = "12",
                            LastName = "Traber",
                            Street = "Hauptstrasse"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 3,
                            CompanyName = "Heeb GmbH",
                            CustomerNr = 0,
                            FirstName = "Lukas",
                            HouseNumber = "2",
                            LastName = "Heeb",
                            Street = "Winkelstrasse"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 4,
                            CompanyName = "CableTec AG",
                            CustomerNr = 0,
                            FirstName = "Eric",
                            HouseNumber = "25",
                            LastName = "Lüchinger",
                            Street = "Bergstrasse"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            CustomerNr = 0,
                            FirstName = "Anton",
                            HouseNumber = "9",
                            LastName = "Segmüller",
                            Street = "Weiherweg"
                        });
                });

            modelBuilder.Entity("db_projektarbeit.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "3456_Haus_Kohl",
                            CustomerId = 1,
                            Date = new DateTime(2020, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Comment = "123_Haus_Tranz",
                            CustomerId = 1,
                            Date = new DateTime(2020, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Comment = "000_Haus_google",
                            CustomerId = 2,
                            Date = new DateTime(2020, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Comment = "403_Haus_Torsten",
                            CustomerId = 3,
                            Date = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Privat",
                            CustomerId = 4,
                            Date = new DateTime(2020, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Comment = "750_Gotinger_Martin",
                            CustomerId = 1,
                            Date = new DateTime(2020, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Comment = "730_Martins",
                            CustomerId = 2,
                            Date = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Comment = "730_Martins",
                            CustomerId = 3,
                            Date = new DateTime(2020, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Brühwiler_Ferienhaus",
                            CustomerId = 4,
                            Date = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Dubli",
                            CustomerId = 1,
                            Date = new DateTime(2020, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Comment = "Butz_Herkingen",
                            CustomerId = 2,
                            Date = new DateTime(2020, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Comment = "Brügger_Baden",
                            CustomerId = 3,
                            Date = new DateTime(2020, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Comment = "Familenfest",
                            CustomerId = 4,
                            Date = new DateTime(2020, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Comment = "642_Gieger_Peter",
                            CustomerId = 1,
                            Date = new DateTime(2020, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Comment = "719_Kratt_Manuel",
                            CustomerId = 2,
                            Date = new DateTime(2020, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Comment = "149_Böhni_Urs",
                            CustomerId = 3,
                            Date = new DateTime(2020, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Comment = "Skiferien",
                            CustomerId = 4,
                            Date = new DateTime(2020, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Comment = "639_Spielman_Gorden",
                            CustomerId = 1,
                            Date = new DateTime(2020, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Comment = "396_Björn_Kortu",
                            CustomerId = 2,
                            Date = new DateTime(2020, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Comment = "999_Karten_Schnutz",
                            CustomerId = 3,
                            Date = new DateTime(2020, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Comment = "Garten_Haus",
                            CustomerId = 4,
                            Date = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Comment = "123_holdergarten_Gerd",
                            CustomerId = 1,
                            Date = new DateTime(2020, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("db_projektarbeit.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Counter")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Counter = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Total = 1m
                        },
                        new
                        {
                            Id = 2,
                            Counter = 3,
                            OrderId = 1,
                            ProductId = 4,
                            Total = 15m
                        },
                        new
                        {
                            Id = 3,
                            Counter = 2,
                            OrderId = 1,
                            ProductId = 5,
                            Total = 2.50m
                        },
                        new
                        {
                            Id = 4,
                            Counter = 1,
                            OrderId = 2,
                            ProductId = 8,
                            Total = 17.69m
                        },
                        new
                        {
                            Id = 5,
                            Counter = 1,
                            OrderId = 3,
                            ProductId = 3,
                            Total = 0m
                        },
                        new
                        {
                            Id = 6,
                            Counter = 3,
                            OrderId = 3,
                            ProductId = 7,
                            Total = 0m
                        },
                        new
                        {
                            Id = 7,
                            Counter = 2,
                            OrderId = 4,
                            ProductId = 8,
                            Total = 0m
                        },
                        new
                        {
                            Id = 8,
                            Counter = 2,
                            OrderId = 5,
                            ProductId = 8,
                            Total = 0m
                        },
                        new
                        {
                            Id = 9,
                            Counter = 2,
                            OrderId = 5,
                            ProductId = 8,
                            Total = 0m
                        },
                        new
                        {
                            Id = 10,
                            Counter = 3,
                            OrderId = 6,
                            ProductId = 10,
                            Total = 0m
                        },
                        new
                        {
                            Id = 11,
                            Counter = 1,
                            OrderId = 6,
                            ProductId = 11,
                            Total = 0m
                        },
                        new
                        {
                            Id = 12,
                            Counter = 3,
                            OrderId = 6,
                            ProductId = 12,
                            Total = 0m
                        },
                        new
                        {
                            Id = 13,
                            Counter = 8,
                            OrderId = 7,
                            ProductId = 3,
                            Total = 0m
                        },
                        new
                        {
                            Id = 14,
                            Counter = 1,
                            OrderId = 7,
                            ProductId = 8,
                            Total = 0m
                        },
                        new
                        {
                            Id = 15,
                            Counter = 2,
                            OrderId = 8,
                            ProductId = 12,
                            Total = 0m
                        },
                        new
                        {
                            Id = 16,
                            Counter = 1,
                            OrderId = 8,
                            ProductId = 1,
                            Total = 0m
                        },
                        new
                        {
                            Id = 17,
                            Counter = 3,
                            OrderId = 9,
                            ProductId = 2,
                            Total = 0m
                        },
                        new
                        {
                            Id = 18,
                            Counter = 2,
                            OrderId = 10,
                            ProductId = 5,
                            Total = 0m
                        },
                        new
                        {
                            Id = 19,
                            Counter = 1,
                            OrderId = 10,
                            ProductId = 12,
                            Total = 0m
                        },
                        new
                        {
                            Id = 20,
                            Counter = 4,
                            OrderId = 11,
                            ProductId = 7,
                            Total = 0m
                        },
                        new
                        {
                            Id = 21,
                            Counter = 1,
                            OrderId = 12,
                            ProductId = 8,
                            Total = 0m
                        },
                        new
                        {
                            Id = 22,
                            Counter = 3,
                            OrderId = 13,
                            ProductId = 9,
                            Total = 0m
                        },
                        new
                        {
                            Id = 23,
                            Counter = 2,
                            OrderId = 13,
                            ProductId = 2,
                            Total = 0m
                        },
                        new
                        {
                            Id = 24,
                            Counter = 1,
                            OrderId = 14,
                            ProductId = 5,
                            Total = 0m
                        },
                        new
                        {
                            Id = 25,
                            Counter = 2,
                            OrderId = 15,
                            ProductId = 11,
                            Total = 0m
                        },
                        new
                        {
                            Id = 26,
                            Counter = 1,
                            OrderId = 15,
                            ProductId = 12,
                            Total = 0m
                        },
                        new
                        {
                            Id = 27,
                            Counter = 1,
                            OrderId = 16,
                            ProductId = 2,
                            Total = 0m
                        },
                        new
                        {
                            Id = 28,
                            Counter = 1,
                            OrderId = 16,
                            ProductId = 3,
                            Total = 0m
                        },
                        new
                        {
                            Id = 29,
                            Counter = 1,
                            OrderId = 17,
                            ProductId = 3,
                            Total = 0m
                        },
                        new
                        {
                            Id = 30,
                            Counter = 1,
                            OrderId = 18,
                            ProductId = 9,
                            Total = 0m
                        },
                        new
                        {
                            Id = 31,
                            Counter = 2,
                            OrderId = 18,
                            ProductId = 3,
                            Total = 0m
                        },
                        new
                        {
                            Id = 32,
                            Counter = 2,
                            OrderId = 19,
                            ProductId = 10,
                            Total = 0m
                        },
                        new
                        {
                            Id = 33,
                            Counter = 2,
                            OrderId = 19,
                            ProductId = 11,
                            Total = 0m
                        },
                        new
                        {
                            Id = 34,
                            Counter = 1,
                            OrderId = 19,
                            ProductId = 12,
                            Total = 0m
                        },
                        new
                        {
                            Id = 35,
                            Counter = 1,
                            OrderId = 20,
                            ProductId = 3,
                            Total = 0m
                        },
                        new
                        {
                            Id = 36,
                            Counter = 3,
                            OrderId = 21,
                            ProductId = 5,
                            Total = 0m
                        },
                        new
                        {
                            Id = 37,
                            Counter = 1,
                            OrderId = 21,
                            ProductId = 8,
                            Total = 0m
                        },
                        new
                        {
                            Id = 38,
                            Counter = 1,
                            OrderId = 22,
                            ProductId = 8,
                            Total = 0m
                        },
                        new
                        {
                            Id = 39,
                            Counter = 2,
                            OrderId = 22,
                            ProductId = 3,
                            Total = 0m
                        });
                });

            modelBuilder.Entity("db_projektarbeit.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR shared.ProductNr");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stuhl mit Armlehnen",
                            GroupId = 2,
                            Price = 140m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2020, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stuhl Comfort",
                            GroupId = 2,
                            Price = 170m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rolli",
                            GroupId = 3,
                            Price = 199.90m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2020, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "RT-9000",
                            GroupId = 6,
                            Price = 360.50m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2020, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Polaroid Thermo",
                            GroupId = 8,
                            Price = 89.90m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2020, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "HP M123XX",
                            GroupId = 9,
                            Price = 349m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "HP M321YY",
                            GroupId = 9,
                            Price = 321m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2020, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Brother Deluxe",
                            GroupId = 9,
                            Price = 430m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2020, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "HP all-in-one",
                            GroupId = 10,
                            Price = 999.90m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2020, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Meier (gelb)",
                            GroupId = 11,
                            Price = 2.90m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2020, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Meier (blau)",
                            GroupId = 11,
                            Price = 2.30m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Meier (grau)",
                            GroupId = 11,
                            Price = 3m,
                            ProductNr = 0
                        });
                });

            modelBuilder.Entity("db_projektarbeit.ProductGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ProductGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Büromöbel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bürostuhl",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Korpus",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Schreibtisch",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Drucker"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Belegdrucker",
                            ParentId = 5
                        },
                        new
                        {
                            Id = 7,
                            Name = "Farbdrucker",
                            ParentId = 5
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fotodrucker",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 9,
                            Name = "Multifunktionsdrucker",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 10,
                            Name = "Toner",
                            ParentId = 5
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ordner"
                        });
                });

            modelBuilder.Entity("db_projektarbeit.Customer", b =>
                {
                    b.HasOne("db_projektarbeit.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("db_projektarbeit.Order", b =>
                {
                    b.HasOne("db_projektarbeit.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("db_projektarbeit.Position", b =>
                {
                    b.HasOne("db_projektarbeit.Order", "Order")
                        .WithMany("Positions")
                        .HasForeignKey("OrderId");

                    b.HasOne("db_projektarbeit.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("db_projektarbeit.Product", b =>
                {
                    b.HasOne("db_projektarbeit.ProductGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("db_projektarbeit.ProductGroup", b =>
                {
                    b.HasOne("db_projektarbeit.ProductGroup", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("db_projektarbeit.Order", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("db_projektarbeit.ProductGroup", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
