// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using db_projektarbeit.Model;

namespace db_projektarbeit.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.HasSequence<int>("CustomerNr", "shared")
                .StartsAt(1000L);

            modelBuilder.HasSequence<int>("ProductNr", "shared")
                .StartsAt(10000L);

            modelBuilder.Entity("db_projektarbeit.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Niederuzwil",
                            Zip = 9244
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bettwiesen",
                            Zip = 9553
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rebstein",
                            Zip = 9445
                        },
                        new
                        {
                            Id = 4,
                            Name = "St. Gallen",
                            Zip = 9000
                        },
                        new
                        {
                            Id = 5,
                            Name = "Goldach",
                            Zip = 9403
                        },
                        new
                        {
                            Id = 6,
                            Name = "Rorschach",
                            Zip = 9400
                        },
                        new
                        {
                            Id = 7,
                            Name = "Au",
                            Zip = 9434
                        },
                        new
                        {
                            Id = 8,
                            Name = "Diepoldsau",
                            Zip = 9444
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sevelen",
                            Zip = 9475
                        },
                        new
                        {
                            Id = 10,
                            Name = "Mörschwil",
                            Zip = 9402
                        },
                        new
                        {
                            Id = 11,
                            Name = "Arbon",
                            Zip = 9320
                        },
                        new
                        {
                            Id = 12,
                            Name = "Tübach",
                            Zip = 9327
                        },
                        new
                        {
                            Id = 13,
                            Name = "Berg (SG)",
                            Zip = 9305
                        },
                        new
                        {
                            Id = 14,
                            Name = "Teufen",
                            Zip = 9053
                        },
                        new
                        {
                            Id = 15,
                            Name = "Gais",
                            Zip = 9056
                        },
                        new
                        {
                            Id = 16,
                            Name = "Rehetobel",
                            Zip = 9038
                        },
                        new
                        {
                            Id = 17,
                            Name = "Trogen",
                            Zip = 9043
                        },
                        new
                        {
                            Id = 18,
                            Name = "Grub",
                            Zip = 9035
                        },
                        new
                        {
                            Id = 19,
                            Name = "Hundwil",
                            Zip = 9064
                        },
                        new
                        {
                            Id = 20,
                            Name = "Untereggen",
                            Zip = 9033
                        },
                        new
                        {
                            Id = 21,
                            Name = "Gossau",
                            Zip = 9200
                        },
                        new
                        {
                            Id = 22,
                            Name = "Flawil",
                            Zip = 9230
                        },
                        new
                        {
                            Id = 23,
                            Name = "Bischofszell",
                            Zip = 9220
                        },
                        new
                        {
                            Id = 24,
                            Name = "Oberbüren",
                            Zip = 9245
                        },
                        new
                        {
                            Id = 25,
                            Name = "Jonschwil",
                            Zip = 9243
                        },
                        new
                        {
                            Id = 26,
                            Name = "Andwil (SG)",
                            Zip = 9204
                        },
                        new
                        {
                            Id = 27,
                            Name = "Hohentannen",
                            Zip = 9216
                        },
                        new
                        {
                            Id = 28,
                            Name = "Rheineck",
                            Zip = 9424
                        },
                        new
                        {
                            Id = 29,
                            Name = "Buchs",
                            Zip = 9470
                        },
                        new
                        {
                            Id = 30,
                            Name = "Thal",
                            Zip = 9425
                        });
                });

            modelBuilder.Entity("db_projektarbeit.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR shared.CustomerNr");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 2, 13, 19, 46, 58, 83, DateTimeKind.Local).AddTicks(3255));

                    b.Property<DateTime>("ValidTo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999));

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CompanyName = "Traber Corp",
                            CustomerNr = 0,
                            FirstName = "Marc",
                            HouseNumber = "12",
                            LastName = "Traber",
                            Street = "Hauptstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            CompanyName = "Heeb GmbH",
                            CustomerNr = 0,
                            FirstName = "Lukas",
                            HouseNumber = "2",
                            LastName = "Heeb",
                            Street = "Winkelstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            CompanyName = "CableTec AG",
                            CustomerNr = 0,
                            FirstName = "Eric",
                            HouseNumber = "25",
                            LastName = "Lüchinger",
                            Street = "Bergstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            CustomerNr = 0,
                            FirstName = "Charlotte",
                            HouseNumber = "9",
                            LastName = "Segmüller",
                            Street = "Weiherweg",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            CompanyName = "Swisscom AG",
                            CustomerNr = 0,
                            FirstName = "Fred",
                            HouseNumber = "2",
                            LastName = "Chatwick",
                            Street = "Burggasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CityId = 6,
                            CustomerNr = 0,
                            FirstName = "Selina",
                            LastName = "Schmidt",
                            Street = "Im Bohl",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CityId = 7,
                            CompanyName = "Setca GmbH",
                            CustomerNr = 0,
                            FirstName = "Paul",
                            HouseNumber = "21",
                            LastName = "Del Curto",
                            Street = "Bahnhofstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CityId = 8,
                            CompanyName = "Bau Köster AG",
                            CustomerNr = 0,
                            FirstName = "Michelle",
                            HouseNumber = "5",
                            LastName = "Terzic",
                            Street = "Settlerstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CityId = 9,
                            CustomerNr = 0,
                            FirstName = "Thorsten",
                            HouseNumber = "2",
                            LastName = "Müller",
                            Street = "Waldweg",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CityId = 10,
                            CompanyName = "Contacta GmbH",
                            CustomerNr = 0,
                            FirstName = "Andreas",
                            HouseNumber = "1",
                            LastName = "Hugentobler",
                            Street = "Hauptstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CityId = 11,
                            CompanyName = "Stadtverwaltung Arbon",
                            CustomerNr = 0,
                            FirstName = "Esther",
                            LastName = "Amgarten",
                            Street = "Rathausplatz",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CityId = 11,
                            CustomerNr = 0,
                            FirstName = "Marianne",
                            HouseNumber = "7",
                            LastName = "Stettler",
                            Street = "Bachstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CityId = 12,
                            CompanyName = "Eon Pharma AG",
                            CustomerNr = 0,
                            FirstName = "Ernst",
                            HouseNumber = "2",
                            LastName = "Hediger",
                            Street = "Dinkelweg",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CityId = 13,
                            CompanyName = "Raiffeisenbank Berg",
                            CustomerNr = 0,
                            FirstName = "Antonio",
                            HouseNumber = "13",
                            LastName = "Perugia",
                            Street = "Schlossgasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CityId = 14,
                            CompanyName = "Stampino AG",
                            CustomerNr = 0,
                            FirstName = "Tina",
                            HouseNumber = "16",
                            LastName = "Mächler",
                            Street = "Hinterwaldstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CityId = 15,
                            CompanyName = "Sport Säntis",
                            CustomerNr = 0,
                            FirstName = "Didier",
                            HouseNumber = "3",
                            LastName = "Cuche",
                            Street = "Unter den Linden",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CityId = 16,
                            CustomerNr = 0,
                            FirstName = "Stefano",
                            LastName = "Dalbacco",
                            Street = "Birkenau",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CityId = 17,
                            CompanyName = "Sägerei Fenk",
                            CustomerNr = 0,
                            FirstName = "Michael",
                            HouseNumber = "10",
                            LastName = "Graf",
                            Street = "Fuchsweg",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CityId = 18,
                            CustomerNr = 0,
                            FirstName = "Angela",
                            HouseNumber = "75",
                            LastName = "Wick",
                            Street = "Dammstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CityId = 19,
                            CompanyName = "Sounddog GmbH",
                            CustomerNr = 0,
                            FirstName = "Patrick",
                            HouseNumber = "5",
                            LastName = "Viera",
                            Street = "Sonnengasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            CityId = 9,
                            CompanyName = "BCJ AG",
                            CustomerNr = 0,
                            FirstName = "Davide",
                            HouseNumber = "7",
                            LastName = "Kluser",
                            Street = "Mühlackerweg",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            CityId = 20,
                            CompanyName = "Enderli Buch AG",
                            CustomerNr = 0,
                            FirstName = "Erich",
                            HouseNumber = "18",
                            LastName = "Kästner",
                            Street = "Feldwiesenstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            CityId = 1,
                            CompanyName = "Blumeria GmbH",
                            CustomerNr = 0,
                            FirstName = "Remo",
                            HouseNumber = "88",
                            LastName = "Santiago",
                            Street = "Bahnhofstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            CityId = 21,
                            CompanyName = "Velomech.ch AG",
                            CustomerNr = 0,
                            FirstName = "Beat",
                            HouseNumber = "1",
                            LastName = "Breu",
                            Street = "Gartenstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            CityId = 8,
                            CustomerNr = 0,
                            FirstName = "Jan",
                            HouseNumber = "62",
                            LastName = "Steiger",
                            Street = "Rorschacherstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            CityId = 22,
                            CompanyName = "Anton Kehrer AG",
                            CustomerNr = 0,
                            FirstName = "Nadine",
                            LastName = "Niedermann",
                            Street = "Am Bühl",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            CityId = 23,
                            CompanyName = "Tres Amigos Ristorante",
                            CustomerNr = 0,
                            FirstName = "Fabian",
                            HouseNumber = "2",
                            LastName = "Buhmann",
                            Street = "Hauptstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            CityId = 24,
                            CompanyName = "Birreria",
                            CustomerNr = 0,
                            FirstName = "Tatjana",
                            HouseNumber = "92",
                            LastName = "Kekarova",
                            Street = "Meistergasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            CityId = 25,
                            CompanyName = "Pizzeria Antonio",
                            CustomerNr = 0,
                            FirstName = "Selina",
                            HouseNumber = "3",
                            LastName = "Gabenthuler",
                            Street = "Postplatz",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            CityId = 26,
                            CustomerNr = 0,
                            FirstName = "Alessia",
                            LastName = "Eichholzer",
                            Street = "Im Tobel",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            CityId = 27,
                            CompanyName = "TeleVisio Corporation",
                            CustomerNr = 0,
                            FirstName = "Tobias",
                            HouseNumber = "32",
                            LastName = "Savello",
                            Street = "Marktgasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            CityId = 11,
                            CompanyName = "CompuTrade GmbH",
                            CustomerNr = 0,
                            FirstName = "Daniel",
                            HouseNumber = "10",
                            LastName = "Brunner",
                            Street = "Bachstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            CityId = 28,
                            CompanyName = "Car Import GmbH",
                            CustomerNr = 0,
                            FirstName = "Ignazio",
                            HouseNumber = "2",
                            LastName = "Torres",
                            Street = "Rheinstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            CityId = 29,
                            CompanyName = "NetworkTrade GmbH",
                            CustomerNr = 0,
                            FirstName = "Rolf",
                            HouseNumber = "56",
                            LastName = "Fringer",
                            Street = "Pizolerstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            CityId = 30,
                            CompanyName = "Gasser Bau AG",
                            CustomerNr = 0,
                            FirstName = "Hubert",
                            HouseNumber = "11",
                            LastName = "Gasser",
                            Street = "Studenbach",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            CityId = 1,
                            CustomerNr = 0,
                            FirstName = "Bernhard",
                            HouseNumber = "22",
                            LastName = "Lutz",
                            Street = "Fähnernweg",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            CityId = 3,
                            CompanyName = "Orthopädie Lüchinger",
                            CustomerNr = 0,
                            FirstName = "Dorothea",
                            HouseNumber = "19",
                            LastName = "Mittermeier",
                            Street = "Hauptstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            CityId = 3,
                            CompanyName = "Sonnenbräu AG",
                            CustomerNr = 0,
                            FirstName = "Fritz",
                            HouseNumber = "5",
                            LastName = "Baumann",
                            Street = "Hinterstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            CityId = 7,
                            CustomerNr = 0,
                            FirstName = "Alexander",
                            HouseNumber = "15",
                            LastName = "Marty",
                            Street = "Kugelgasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            CityId = 11,
                            CustomerNr = 0,
                            FirstName = "Manuel",
                            HouseNumber = "28",
                            LastName = "Stähli",
                            Street = "Lindenweg",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            CityId = 15,
                            CustomerNr = 9001,
                            FirstName = "Dominic",
                            HouseNumber = "32",
                            LastName = "Kunz",
                            Street = "Grubstrasse",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2021, 2, 6, 19, 46, 58, 83, DateTimeKind.Local).AddTicks(3255)
                        },
                        new
                        {
                            Id = 42,
                            CityId = 15,
                            CustomerNr = 9001,
                            FirstName = "Dominic",
                            HouseNumber = "9",
                            LastName = "Kunz",
                            Street = "Grabweg",
                            ValidFrom = new DateTime(2021, 2, 6, 19, 46, 58, 83, DateTimeKind.Local).AddTicks(3255),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            CityId = 5,
                            CompanyName = "Weber und Söhne",
                            CustomerNr = 9002,
                            FirstName = "Christian",
                            LastName = "Weber",
                            Street = "Kleinweg",
                            ValidFrom = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValidTo = new DateTime(2021, 1, 4, 19, 46, 58, 83, DateTimeKind.Local).AddTicks(3255)
                        },
                        new
                        {
                            Id = 44,
                            CityId = 5,
                            CompanyName = "Weber und Söhne",
                            CustomerNr = 9002,
                            FirstName = "Christian",
                            HouseNumber = "500",
                            LastName = "Weber",
                            Street = "Grossweg",
                            ValidFrom = new DateTime(2021, 1, 4, 19, 46, 58, 83, DateTimeKind.Local).AddTicks(3255),
                            ValidTo = new DateTime(2021, 2, 11, 19, 46, 58, 83, DateTimeKind.Local).AddTicks(3255)
                        },
                        new
                        {
                            Id = 45,
                            CityId = 5,
                            CompanyName = "Weber AG",
                            CustomerNr = 9002,
                            FirstName = "Christian",
                            HouseNumber = "500",
                            LastName = "Weber",
                            Street = "Grossweg",
                            ValidFrom = new DateTime(2021, 2, 11, 19, 46, 58, 83, DateTimeKind.Local).AddTicks(3255),
                            ValidTo = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("db_projektarbeit.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "3456_Haus_Kohl",
                            CustomerId = 1,
                            Date = new DateTime(2020, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Comment = "123_Haus_Tranz",
                            CustomerId = 1,
                            Date = new DateTime(2020, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Comment = "000_Haus_google",
                            CustomerId = 2,
                            Date = new DateTime(2020, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Comment = "403_Haus_Torsten",
                            CustomerId = 3,
                            Date = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Privat",
                            CustomerId = 4,
                            Date = new DateTime(2020, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Comment = "750_Gotinger_Martin",
                            CustomerId = 1,
                            Date = new DateTime(2020, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Comment = "730_Martins",
                            CustomerId = 2,
                            Date = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Comment = "730_Martins",
                            CustomerId = 3,
                            Date = new DateTime(2020, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Brühwiler_Ferienhaus",
                            CustomerId = 4,
                            Date = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Dubli",
                            CustomerId = 1,
                            Date = new DateTime(2020, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Comment = "Butz_Herkingen",
                            CustomerId = 2,
                            Date = new DateTime(2020, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Comment = "Brügger_Baden",
                            CustomerId = 3,
                            Date = new DateTime(2020, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Comment = "Familenfest",
                            CustomerId = 4,
                            Date = new DateTime(2020, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Comment = "642_Gieger_Peter",
                            CustomerId = 1,
                            Date = new DateTime(2020, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Comment = "719_Kratt_Manuel",
                            CustomerId = 2,
                            Date = new DateTime(2020, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Comment = "149_Böhni_Urs",
                            CustomerId = 3,
                            Date = new DateTime(2020, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Comment = "Skiferien",
                            CustomerId = 4,
                            Date = new DateTime(2020, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Comment = "639_Spielman_Gorden",
                            CustomerId = 1,
                            Date = new DateTime(2020, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Comment = "396_Björn_Kortu",
                            CustomerId = 2,
                            Date = new DateTime(2020, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Comment = "999_Karten_Schnutz",
                            CustomerId = 3,
                            Date = new DateTime(2020, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Comment = "Garten_Haus",
                            CustomerId = 4,
                            Date = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Comment = "123_holdergarten_Gerd",
                            CustomerId = 1,
                            Date = new DateTime(2020, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("db_projektarbeit.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 1,
                            OrderId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Count = 3,
                            OrderId = 1,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 3,
                            Count = 2,
                            OrderId = 1,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 4,
                            Count = 1,
                            OrderId = 2,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 5,
                            Count = 1,
                            OrderId = 3,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 6,
                            Count = 3,
                            OrderId = 3,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 7,
                            Count = 2,
                            OrderId = 4,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 8,
                            Count = 2,
                            OrderId = 5,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 9,
                            Count = 2,
                            OrderId = 5,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 10,
                            Count = 3,
                            OrderId = 6,
                            ProductId = 10
                        },
                        new
                        {
                            Id = 11,
                            Count = 1,
                            OrderId = 6,
                            ProductId = 11
                        },
                        new
                        {
                            Id = 12,
                            Count = 3,
                            OrderId = 6,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 13,
                            Count = 8,
                            OrderId = 7,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 14,
                            Count = 1,
                            OrderId = 7,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 15,
                            Count = 2,
                            OrderId = 8,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 16,
                            Count = 1,
                            OrderId = 8,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 17,
                            Count = 3,
                            OrderId = 9,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 18,
                            Count = 2,
                            OrderId = 10,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 19,
                            Count = 1,
                            OrderId = 10,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 20,
                            Count = 4,
                            OrderId = 11,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 21,
                            Count = 1,
                            OrderId = 12,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 22,
                            Count = 3,
                            OrderId = 13,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 23,
                            Count = 2,
                            OrderId = 13,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 24,
                            Count = 1,
                            OrderId = 14,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 25,
                            Count = 2,
                            OrderId = 15,
                            ProductId = 11
                        },
                        new
                        {
                            Id = 26,
                            Count = 1,
                            OrderId = 15,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 27,
                            Count = 1,
                            OrderId = 16,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 28,
                            Count = 1,
                            OrderId = 16,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 29,
                            Count = 1,
                            OrderId = 17,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 30,
                            Count = 1,
                            OrderId = 18,
                            ProductId = 9
                        },
                        new
                        {
                            Id = 31,
                            Count = 2,
                            OrderId = 18,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 32,
                            Count = 2,
                            OrderId = 19,
                            ProductId = 10
                        },
                        new
                        {
                            Id = 33,
                            Count = 2,
                            OrderId = 19,
                            ProductId = 11
                        },
                        new
                        {
                            Id = 34,
                            Count = 1,
                            OrderId = 19,
                            ProductId = 12
                        },
                        new
                        {
                            Id = 35,
                            Count = 1,
                            OrderId = 20,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 36,
                            Count = 3,
                            OrderId = 21,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 37,
                            Count = 1,
                            OrderId = 21,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 38,
                            Count = 1,
                            OrderId = 22,
                            ProductId = 8
                        },
                        new
                        {
                            Id = 39,
                            Count = 2,
                            OrderId = 22,
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("db_projektarbeit.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductNr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR shared.ProductNr");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stuhl mit Armlehnen",
                            GroupId = 2,
                            Price = 140m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2020, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Stuhl Comfort",
                            GroupId = 2,
                            Price = 170m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2020, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rolli",
                            GroupId = 3,
                            Price = 199.90m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2020, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "RT-9000",
                            GroupId = 6,
                            Price = 360.50m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2020, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Polaroid Thermo",
                            GroupId = 8,
                            Price = 89.90m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2020, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "HP M123XX",
                            GroupId = 9,
                            Price = 349m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "HP M321YY",
                            GroupId = 9,
                            Price = 321m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2020, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Brother Deluxe",
                            GroupId = 9,
                            Price = 430m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2020, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "HP all-in-one",
                            GroupId = 10,
                            Price = 999.90m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2020, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Meier (gelb)",
                            GroupId = 11,
                            Price = 2.90m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateTime(2020, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Meier (blau)",
                            GroupId = 11,
                            Price = 2.30m,
                            ProductNr = 0
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Meier (grau)",
                            GroupId = 11,
                            Price = 3m,
                            ProductNr = 0
                        });
                });

            modelBuilder.Entity("db_projektarbeit.ProductGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("ProductGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Büromöbel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bürostuhl",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Korpus",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Schreibtisch",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Drucker"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Belegdrucker",
                            ParentId = 5
                        },
                        new
                        {
                            Id = 7,
                            Name = "Farbdrucker",
                            ParentId = 5
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fotodrucker",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 9,
                            Name = "Multifunktionsdrucker",
                            ParentId = 7
                        },
                        new
                        {
                            Id = 10,
                            Name = "Toner",
                            ParentId = 5
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ordner"
                        });
                });

            modelBuilder.Entity("db_projektarbeit.Customer", b =>
                {
                    b.HasOne("db_projektarbeit.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("db_projektarbeit.Order", b =>
                {
                    b.HasOne("db_projektarbeit.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("db_projektarbeit.Position", b =>
                {
                    b.HasOne("db_projektarbeit.Order", "Order")
                        .WithMany("Positions")
                        .HasForeignKey("OrderId");

                    b.HasOne("db_projektarbeit.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("db_projektarbeit.Product", b =>
                {
                    b.HasOne("db_projektarbeit.ProductGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("db_projektarbeit.ProductGroup", b =>
                {
                    b.HasOne("db_projektarbeit.ProductGroup", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("db_projektarbeit.Order", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("db_projektarbeit.ProductGroup", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
